/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group11.auth;

import com.group11.config.EmailValidate;
import com.group11.config.MysqlConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author ishan
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContactNumber = new javax.swing.JTextField();
        txtEmailSignUp = new javax.swing.JTextField();
        txtPasswordSignUp = new javax.swing.JPasswordField();
        txtConfirmPasswordSignUp = new javax.swing.JPasswordField();
        cmbxPosition = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarReason = new javax.swing.JTextArea();
        btnClearSignUp = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        txtName1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmailSignUp = new javax.swing.JLabel();
        lblPasswordSignUp = new javax.swing.JLabel();
        lblConfirmPasswordSignUp = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblReason1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setBackground(new java.awt.Color(255, 255, 255));

        cmbxPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "Staff Member", "Teacher", "Student", "Parent" }));
        cmbxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxPositionActionPerformed(evt);
            }
        });

        txtarReason.setColumns(20);
        txtarReason.setRows(5);
        jScrollPane2.setViewportView(txtarReason);

        btnClearSignUp.setBackground(new java.awt.Color(56, 182, 255));
        btnClearSignUp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClearSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnClearSignUp.setText("Clear");
        btnClearSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSignUpActionPerformed(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(56, 182, 255));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnSignIn.setBackground(new java.awt.Color(56, 182, 255));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("Click To Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(20, 70, 137));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration Form");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name :");

        lblEmailSignUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailSignUp.setText("E-mail :");

        lblPasswordSignUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPasswordSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordSignUp.setText("Password :");

        lblConfirmPasswordSignUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblConfirmPasswordSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPasswordSignUp.setText("Confirm Password :");

        lblContactNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContactNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblContactNumber.setText("Contact Number :");

        lblPosition.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(255, 255, 255));
        lblPosition.setText("Position :");

        lblReason1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReason1.setForeground(new java.awt.Color(255, 255, 255));
        lblReason1.setText("Reason To Join :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblConfirmPasswordSignUp)
                            .addComponent(lblEmailSignUp)
                            .addComponent(lblPasswordSignUp)
                            .addComponent(lblContactNumber)
                            .addComponent(lblPosition)
                            .addComponent(lblReason1))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lblPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblConfirmPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblReason1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnClearSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(862, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtConfirmPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSignUpActionPerformed
        if (evt.getSource() == btnClearSignUp) {
            txtEmailSignUp.setText("");
            txtPasswordSignUp.setText("");
            txtConfirmPasswordSignUp.setText("");
            txtContactNumber.setText("");
            cmbxPosition.setSelectedIndex(0);
            txtarReason.setText("");
            txtContactNumber.setText("");
        }
    }//GEN-LAST:event_btnClearSignUpActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        if (evt.getSource() == btnSignUp) {
            char[] pwdText = txtPasswordSignUp.getPassword();
            String pwd = new String(pwdText);
            char[] conformPwdText = txtConfirmPasswordSignUp.getPassword();
            String conformPwd = new String(conformPwdText);
            String email = txtEmailSignUp.getText();
            String fullName = txtContactNumber.getText();
            String reasonToJoin = txtarReason.getText();
            int positionSelectionIndex = cmbxPosition.getSelectedIndex();
            String contactNumber = txtContactNumber.getText();

            //check all fields are not empty
            if(email.equals("")||fullName.equals("")||reasonToJoin.equals("")||pwd.equals("") ||contactNumber.equals("")){
                JOptionPane.showMessageDialog(this, "All fields must not empty");

            }
            //validate email
            else if(!EmailValidate.patternMatches(email)){
                JOptionPane.showMessageDialog(this, "Email must be valid");
            }
            //validate password
            else if(!pwd.equals(conformPwd)){
                JOptionPane.showMessageDialog(this, "password must be match");
            }
            //validate position selection
            else if(positionSelectionIndex==0){
                JOptionPane.showMessageDialog(this, "select position from the list");
            }
            else{
                //sava data to database
                try {
                    Connection conn = MysqlConnect.ConnectDB();
                    String query = " insert into system_users (full_name, email, login_password, position, reason_to_join, contact_no, aprove_status)"
                    + " values (?, ?, ?, ?, ?,?,?)";

                    PreparedStatement preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setString(1, fullName);
                    preparedStmt.setString(2, email);
                    preparedStmt.setString(3, pwd);
                    preparedStmt.setInt(4, positionSelectionIndex);
                    preparedStmt.setString(5, reasonToJoin);
                    preparedStmt.setString(6, contactNumber);
                    preparedStmt.setInt(7, 0);

                    preparedStmt.execute();
                    conn.close();

                    txtEmailSignUp.setText("");
                    txtPasswordSignUp.setText("");
                    txtConfirmPasswordSignUp.setText("");
                    txtContactNumber.setText("");
                    cmbxPosition.setSelectedIndex(0);
                    txtarReason.setText("");
                    txtContactNumber.setText("");

                    JOptionPane.showMessageDialog(this, "account created");
                    dispose();
                    new SignIn().setVisible(true);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }

        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        if(evt.getSource()==btnSignIn){
            dispose();
            new SignIn().setVisible(true);
        }
    }//GEN-LAST:event_btnSignInActionPerformed

    private void cmbxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxPositionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearSignUp;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox<String> cmbxPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConfirmPasswordSignUp;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblEmailSignUp;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPasswordSignUp;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblReason1;
    private javax.swing.JPasswordField txtConfirmPasswordSignUp;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmailSignUp;
    private javax.swing.JTextField txtName1;
    private javax.swing.JPasswordField txtPasswordSignUp;
    private javax.swing.JTextArea txtarReason;
    // End of variables declaration//GEN-END:variables
}
